 'use client';
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/demo-model.glb -o src/components/Model.tsx -t 
*/

import React, { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

export function Model(props: JSX.IntrinsicElements['group']) {
  // Load the GLTF and render its root scene to avoid relying on specific node names
  const gltf = useGLTF('/models/car/source/car.glb') as GLTF
  return (
    <group {...props} dispose={null}>
      <primitive object={gltf.scene} />
    </group>
  )
}

useGLTF.preload('/models/car/source/car.glb')
